services:
  - type: web
    name: football-prediction-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python run.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: APIFOOTBALL_API_KEY
        value: 908ca1caaca4f5470f8c9d7f01a02d66fa06d149e77627804796c4f12568a485
    autoDeploy: true
    region: oregon
    plan: free